### ISSUE TITLE
Unable to create an instance :(

### ISSUE THREAD

**Issue by joncfoo** [rstudio/fuzzbucket#53]
```
❯ fuzzbucket-client -Dj create -c ubuntu18
# fuzzbucket:DEBUG:2020-07-29T090912:: attempting request user='joncfoo' method='POST' url='https://secret-squirrel'
# fuzzbucket:ERROR:2020-07-29T090926:: command 'create' failed err=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```

The debug flag doesn't provide much help :sob: 

Will try to diagnose.

**Comment by joncfoo** [comment]
```
Traceback (most recent call last):
  File "/home/jcurran/Code/rstudio.com/fuzzbucket/fuzzbucket_client/__main__.py", line 399, in create
    with self._urlopen(req) as response:
  File "/usr/lib64/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/jcurran/Code/rstudio.com/fuzzbucket/fuzzbucket_client/__main__.py", line 567, in _urlopen
    with urllib.request.urlopen(request) as response:
  File "/usr/lib64/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib64/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib64/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
# fuzzbucket:ERROR:2020-07-29T094544:: command 'create' failed err=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
```

Seems the API is throwing a 500.

**Comment by lucasrod16** [comment]
I encountered this same error with the current latest version 0.15.0. Downgrading to 0.13.0 resolved the issue for me
